name: Deployment Workflow
on:
  push:
    branches: [justin-dev]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/dev/10days-dev/10days-project-2023
            eval `ssh-agent -s`
            ssh-add ~/.ssh/id_keyid
            git pull origin justin-dev
            git status
            pnpm install
            rm -rf .next
            export GOOGLE_CLIENT_ID= ${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET= ${{ secrets.GOOGLE_CLIENT_SECRET }}
            pnpm build
            pm2 restart 10dev